[2024-03-01T21:20:50.291+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-03-01T21:20:50.296+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-03-01T21:20:50.297+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 6
[2024-03-01T21:20:50.306+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-02-28 00:00:00+00:00
[2024-03-01T21:20:50.311+0000] {standard_task_runner.py:60} INFO - Started process 6840 to run task
[2024-03-01T21:20:50.314+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2024-02-28T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp6nflrsvq']
[2024-03-01T21:20:50.316+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask create_postgres_table
[2024-03-01T21:20:50.356+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-02-28T00:00:00+00:00 [running]> on host 417e643aed36
[2024-03-01T21:20:51.144+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dn' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-28T00:00:00+00:00'
[2024-03-01T21:20:51.145+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key(dt,dag_id)
            )
        
[2024-03-01T21:20:51.157+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-01T21:20:51.176+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-01T21:20:51.239+0000] {sql.py:457} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key(dt,dag_id)
            )
        , parameters: None
[2024-03-01T21:20:51.323+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.

[2024-03-01T21:20:51.333+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20240228T000000, start_date=20240301T212050, end_date=20240301T212051
[2024-03-01T21:20:51.344+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 88 for task create_postgres_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.
; 6840)
[2024-03-01T21:20:51.382+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-01T21:20:51.402+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
