[2024-03-04T14:49:19.392+0000] {processor.py:161} INFO - Started process (PID=86675) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:19.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:19.406+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:19.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:19.421+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:19.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2024-03-04T14:49:19.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:19.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.136 seconds
[2024-03-04T14:49:25.435+0000] {processor.py:161} INFO - Started process (PID=86680) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:25.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:25.441+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:25.440+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:25.465+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:25.462+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 4
    from airflow.operators.python
                                 ^
SyntaxError: invalid syntax
[2024-03-04T14:49:25.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:25.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.071 seconds
[2024-03-04T14:49:30.278+0000] {processor.py:161} INFO - Started process (PID=86715) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:30.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:30.289+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:30.286+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:30.308+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:30.305+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 4
    from airflow.operators.python import 
                                         ^
SyntaxError: invalid syntax
[2024-03-04T14:49:30.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:30.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.082 seconds
[2024-03-04T14:49:37.571+0000] {processor.py:161} INFO - Started process (PID=86726) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:37.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:37.575+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:37.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:37.610+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:37.596+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 4, in <module>
    from airflow.operators.python import Python
ImportError: cannot import name 'Python' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py)
[2024-03-04T14:49:37.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:37.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.138 seconds
[2024-03-04T14:49:42.768+0000] {processor.py:161} INFO - Started process (PID=86731) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:42.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:42.773+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:42.772+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:42.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:42.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.091 seconds
[2024-03-04T14:49:52.064+0000] {processor.py:161} INFO - Started process (PID=86736) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:52.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:52.074+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:52.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:52.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:52.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.069 seconds
[2024-03-04T14:49:58.233+0000] {processor.py:161} INFO - Started process (PID=86741) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:58.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:49:58.238+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:49:58.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:58.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:49:58.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.081 seconds
[2024-03-04T14:50:01.170+0000] {processor.py:161} INFO - Started process (PID=86776) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:01.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:01.180+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:01.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:01.201+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:01.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 7
    'owner':
           ^
SyntaxError: expression expected after dictionary key and ':'
[2024-03-04T14:50:01.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:01.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.097 seconds
[2024-03-04T14:50:07.621+0000] {processor.py:161} INFO - Started process (PID=86787) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:07.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:07.653+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:07.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:07.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:07.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.268 seconds
[2024-03-04T14:50:14.608+0000] {processor.py:161} INFO - Started process (PID=86792) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:14.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:14.615+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:14.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:14.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:14.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.078 seconds
[2024-03-04T14:50:20.916+0000] {processor.py:161} INFO - Started process (PID=86797) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:20.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:20.923+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:20.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:20.934+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:20.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 8
    re
     ^
SyntaxError: ':' expected after dictionary key
[2024-03-04T14:50:20.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:20.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.095 seconds
[2024-03-04T14:50:28.098+0000] {processor.py:161} INFO - Started process (PID=86802) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:28.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:28.104+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:28.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:28.124+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:28.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 8
    'retry'
          ^
SyntaxError: ':' expected after dictionary key
[2024-03-04T14:50:28.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:28.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.076 seconds
[2024-03-04T14:50:32.761+0000] {processor.py:161} INFO - Started process (PID=86837) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:32.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:32.767+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:32.765+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:32.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:32.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.121 seconds
[2024-03-04T14:50:38.995+0000] {processor.py:161} INFO - Started process (PID=86848) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:38.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:38.999+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:38.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:39.021+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:39.015+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 9
    'retry_delay'
                ^
SyntaxError: ':' expected after dictionary key
[2024-03-04T14:50:39.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:39.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.069 seconds
[2024-03-04T14:50:42.173+0000] {processor.py:161} INFO - Started process (PID=86853) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:42.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:42.178+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:42.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:42.189+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:42.187+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 9
    'retry_delay': 
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-03-04T14:50:42.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:42.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.082 seconds
[2024-03-04T14:50:51.517+0000] {processor.py:161} INFO - Started process (PID=86858) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:51.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:51.523+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:51.522+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:51.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:51.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.068 seconds
[2024-03-04T14:50:59.752+0000] {processor.py:161} INFO - Started process (PID=86863) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:59.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:50:59.757+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:59.756+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:59.769+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:50:59.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12
    with DAG
            ^
SyntaxError: expected ':'
[2024-03-04T14:50:59.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:50:59.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.073 seconds
[2024-03-04T14:51:08.588+0000] {processor.py:161} INFO - Started process (PID=86904) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:08.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:08.600+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:08.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:08.632+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:08.627+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 13
    
    ^
IndentationError: expected an indented block after 'with' statement on line 12
[2024-03-04T14:51:08.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:08.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.124 seconds
[2024-03-04T14:51:17.742+0000] {processor.py:161} INFO - Started process (PID=86909) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:17.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:17.832+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:17.821+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:17.919+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:17.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:51:17.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:18.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.345 seconds
[2024-03-04T14:51:23.250+0000] {processor.py:161} INFO - Started process (PID=86914) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:23.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:23.255+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:23.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:23.267+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:23.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14
    dag_id=
           ^
SyntaxError: invalid syntax
[2024-03-04T14:51:23.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:23.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.091 seconds
[2024-03-04T14:51:29.422+0000] {processor.py:161} INFO - Started process (PID=86919) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:29.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:29.427+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:29.427+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:29.441+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:29.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:51:29.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:29.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.071 seconds
[2024-03-04T14:51:45.224+0000] {processor.py:161} INFO - Started process (PID=86960) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:45.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:45.230+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:45.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:45.244+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:45.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:51:45.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:45.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.081 seconds
[2024-03-04T14:51:53.479+0000] {processor.py:161} INFO - Started process (PID=86965) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:53.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:53.502+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:53.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:53.537+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:53.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:51:53.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:53.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.141 seconds
[2024-03-04T14:51:57.649+0000] {processor.py:161} INFO - Started process (PID=86970) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:57.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:51:57.664+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:57.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:57.675+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:51:57.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15
    start_date=
               ^
SyntaxError: invalid syntax
[2024-03-04T14:51:57.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:51:57.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.094 seconds
[2024-03-04T14:52:03.387+0000] {processor.py:161} INFO - Started process (PID=87005) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:03.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:52:03.392+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:03.391+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:03.423+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:03.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:52:03.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:03.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.083 seconds
[2024-03-04T14:52:25.115+0000] {processor.py:161} INFO - Started process (PID=87016) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:25.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:52:25.126+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:25.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:25.166+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:25.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:52:25.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:25.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.139 seconds
[2024-03-04T14:52:42.980+0000] {processor.py:161} INFO - Started process (PID=87057) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:42.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:52:42.998+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:42.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:43.025+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:52:43.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:52:43.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:52:43.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.105 seconds
[2024-03-04T14:53:13.871+0000] {processor.py:161} INFO - Started process (PID=87098) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:13.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:53:13.876+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:53:13.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:13.885+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:53:13.883+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:53:13.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:13.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.069 seconds
[2024-03-04T14:53:44.831+0000] {processor.py:161} INFO - Started process (PID=87139) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:44.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:53:44.838+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:53:44.836+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:44.849+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:53:44.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:53:44.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:53:44.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.068 seconds
[2024-03-04T14:54:15.917+0000] {processor.py:161} INFO - Started process (PID=87180) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:15.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:54:15.927+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:15.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:15.944+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:15.938+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:54:15.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:15.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.104 seconds
[2024-03-04T14:54:31.402+0000] {processor.py:161} INFO - Started process (PID=87185) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:31.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:54:31.409+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:31.408+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:31.422+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:31.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12
    def get_
            ^
SyntaxError: expected '('
[2024-03-04T14:54:31.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:31.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.101 seconds
[2024-03-04T14:54:39.269+0000] {processor.py:161} INFO - Started process (PID=87226) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:39.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:54:39.280+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:39.279+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:39.292+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:39.290+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14
    with DAG() as dag:
    ^^^^
IndentationError: expected an indented block after function definition on line 12
[2024-03-04T14:54:39.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:39.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.096 seconds
[2024-03-04T14:54:50.629+0000] {processor.py:161} INFO - Started process (PID=87231) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:50.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:54:50.637+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:50.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:50.658+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:50.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:54:50.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:50.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.086 seconds
[2024-03-04T14:54:58.923+0000] {processor.py:161} INFO - Started process (PID=87236) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:58.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:54:58.929+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:58.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:58.949+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:54:58.946+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:54:58.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:54:58.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.084 seconds
[2024-03-04T14:55:02.290+0000] {processor.py:161} INFO - Started process (PID=87241) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:02.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:02.295+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:02.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:02.310+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:02.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:02.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:02.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.076 seconds
[2024-03-04T14:55:06.573+0000] {processor.py:161} INFO - Started process (PID=87252) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:06.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:06.610+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:06.608+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:06.690+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:06.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:06.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:06.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.370 seconds
[2024-03-04T14:55:14.894+0000] {processor.py:161} INFO - Started process (PID=87287) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:14.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:14.899+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:14.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:14.912+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:14.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:14.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:14.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.083 seconds
[2024-03-04T14:55:21.118+0000] {processor.py:161} INFO - Started process (PID=87292) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:21.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:21.123+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:21.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:21.134+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:21.132+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14
    print(f"scikit-learn with version: {}")
                                          ^
SyntaxError: f-string: empty expression not allowed
[2024-03-04T14:55:21.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:21.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.071 seconds
[2024-03-04T14:55:31.513+0000] {processor.py:161} INFO - Started process (PID=87297) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:31.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:31.517+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:31.517+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:31.532+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:31.529+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:31.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:31.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.134 seconds
[2024-03-04T14:55:37.713+0000] {processor.py:161} INFO - Started process (PID=87307) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:37.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:37.747+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:37.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:37.796+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:37.793+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:37.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:37.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.196 seconds
[2024-03-04T14:55:47.709+0000] {processor.py:161} INFO - Started process (PID=87342) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:47.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:55:47.714+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:47.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:47.730+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:55:47.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 16, in <module>
    with DAG() as dag:
         ^^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-03-04T14:55:47.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:55:47.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.090 seconds
[2024-03-04T14:56:11.789+0000] {processor.py:161} INFO - Started process (PID=87383) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:11.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:56:11.794+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:11.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:11.816+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:11.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
IndentationError: expected an indented block after 'with' statement on line 16
[2024-03-04T14:56:11.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:11.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.075 seconds
[2024-03-04T14:56:16.050+0000] {processor.py:161} INFO - Started process (PID=87388) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:16.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:56:16.058+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:16.057+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:16.069+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:16.067+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 25
    
    ^
IndentationError: expected an indented block after 'with' statement on line 16
[2024-03-04T14:56:16.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:16.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.120 seconds
[2024-03-04T14:56:20.231+0000] {processor.py:161} INFO - Started process (PID=87393) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:20.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:56:20.237+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:20.236+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:20.246+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:20.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    get_sklearn = 
                  ^
SyntaxError: invalid syntax
[2024-03-04T14:56:20.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:20.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.091 seconds
[2024-03-04T14:56:24.603+0000] {processor.py:161} INFO - Started process (PID=87398) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:24.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:56:24.612+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:24.608+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:24.661+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:24.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23, in <module>
    get_sklearn = PythonOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-03-04T14:56:24.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:24.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.114 seconds
[2024-03-04T14:56:30.754+0000] {processor.py:161} INFO - Started process (PID=87403) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:30.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:56:30.760+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:30.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:30.810+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:56:30.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:56:30.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:56:30.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.133 seconds
[2024-03-04T14:57:01.823+0000] {processor.py:161} INFO - Started process (PID=87444) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:01.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:57:01.840+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:57:01.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:01.865+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:57:01.863+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:57:01.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:01.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.080 seconds
[2024-03-04T14:57:32.689+0000] {processor.py:161} INFO - Started process (PID=87485) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:32.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:57:32.692+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:57:32.692+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:32.729+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:57:32.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:57:32.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:57:32.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.079 seconds
[2024-03-04T14:58:03.556+0000] {processor.py:161} INFO - Started process (PID=87526) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:03.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:58:03.562+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:58:03.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:03.579+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:58:03.577+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:58:03.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:03.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.081 seconds
[2024-03-04T14:58:34.410+0000] {processor.py:161} INFO - Started process (PID=87568) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:34.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:58:34.415+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:58:34.414+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:34.434+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:58:34.432+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:58:34.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:58:34.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.083 seconds
[2024-03-04T14:59:05.134+0000] {processor.py:161} INFO - Started process (PID=87609) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:05.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:59:05.138+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:05.137+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:05.163+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:05.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:59:05.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:05.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.066 seconds
[2024-03-04T14:59:36.150+0000] {processor.py:161} INFO - Started process (PID=87650) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:36.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:59:36.154+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:36.153+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:36.174+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:36.171+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 24, in <module>
    task
NameError: name 'task' is not defined
[2024-03-04T14:59:36.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:36.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.064 seconds
[2024-03-04T14:59:53.287+0000] {processor.py:161} INFO - Started process (PID=87691) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:53.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T14:59:53.314+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:53.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:53.367+0000] {logging_mixin.py:188} INFO - [2024-03-04T14:59:53.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 25
    )
    ^
SyntaxError: invalid syntax
[2024-03-04T14:59:53.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T14:59:53.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.334 seconds
[2024-03-04T15:00:15.634+0000] {processor.py:161} INFO - Started process (PID=87703) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:15.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:00:15.647+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:15.646+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:15.731+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:15.717+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23, in <module>
    get_sklearn = PythonOperator(
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-03-04T15:00:15.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:15.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.231 seconds
[2024-03-04T15:00:28.516+0000] {processor.py:161} INFO - Started process (PID=87738) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:28.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:00:28.522+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:28.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:28.539+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:28.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 26
    )
    ^
SyntaxError: invalid syntax
[2024-03-04T15:00:28.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:28.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.141 seconds
[2024-03-04T15:00:33.803+0000] {processor.py:161} INFO - Started process (PID=87743) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:33.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:00:33.821+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:33.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:33.878+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:33.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 25, in <module>
    python_callable=get_sklearn()
                    ^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2024-03-04T15:00:33.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:34.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.498 seconds
[2024-03-04T15:00:39.639+0000] {processor.py:161} INFO - Started process (PID=87754) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:39.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:00:39.644+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:39.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:39.706+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_V01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:40.071+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.070+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_with_python_dependencies_V01
[2024-03-04T15:00:40.079+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.078+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_with_python_dependencies_V01
[2024-03-04T15:00:40.082+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.082+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_with_python_dependencies_V01
[2024-03-04T15:00:40.083+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.083+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-04T15:00:40.099+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.098+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_with_python_dependencies_V01
[2024-03-04T15:00:40.115+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:40.115+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_V01 to 2024-03-03 00:00:00+00:00, run_after=2024-03-04 00:00:00+00:00
[2024-03-04T15:00:40.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.500 seconds
[2024-03-04T15:00:46.196+0000] {processor.py:161} INFO - Started process (PID=87759) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:46.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:00:46.231+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:46.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:46.272+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:00:46.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 28, in <module>
    get_sklearn()
TypeError: 'PythonOperator' object is not callable
[2024-03-04T15:00:46.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:00:46.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.153 seconds
[2024-03-04T15:01:10.235+0000] {processor.py:161} INFO - Started process (PID=87800) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:10.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:01:10.252+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:10.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:10.299+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_V01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:10.361+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:10.361+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-04T15:01:10.449+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:10.449+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_V01 to 2024-03-03 00:00:00+00:00, run_after=2024-03-04 00:00:00+00:00
[2024-03-04T15:01:10.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.243 seconds
[2024-03-04T15:01:41.602+0000] {processor.py:161} INFO - Started process (PID=87842) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:41.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:01:41.610+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:41.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:41.685+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_V01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:01:41.785+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:41.784+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-04T15:01:41.861+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:01:41.861+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_V01 to 2024-03-03 00:00:00+00:00, run_after=2024-03-04 00:00:00+00:00
[2024-03-04T15:01:41.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.316 seconds
[2024-03-04T15:02:12.164+0000] {processor.py:161} INFO - Started process (PID=87883) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:02:12.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-04T15:02:12.170+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:02:12.170+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:02:12.197+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_V01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-04T15:02:12.236+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:02:12.236+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-04T15:02:12.283+0000] {logging_mixin.py:188} INFO - [2024-03-04T15:02:12.283+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_V01 to 2024-03-03 00:00:00+00:00, run_after=2024-03-04 00:00:00+00:00
[2024-03-04T15:02:12.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.150 seconds
